// frontend/src/App.tsx
import { useEffect, useState } from 'react'

interface HealthResponse {
  status?: string;
  detail?: string;
  [key: string]: unknown;
}

function App() {
  const [healthData, setHealthData] = useState<HealthResponse | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/v1/health/')
      .then((res) => {
        if (!res.ok) {
          throw new Error(`HTTP error! Estado: ${res.status}`);
        }
        return res.json();
      })
      .then((data: HealthResponse) => {
        setHealthData(data);
        setLoading(false);
      })
      .catch((err: Error) => {
        setError(err.message);
        setLoading(false);
      });
  }, []);

  return (
    <div style={{ maxWidth: '600px', margin: '3rem auto', padding: '1.5rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1 style={{ textAlign: 'center', marginBottom: '0.5rem' }}>GameStore</h1>
      <h3 style={{ textAlign: 'center', color: '#666', marginTop: 0 }}>React + TypeScript + Docker</h3>
      
      <div style={{ marginTop: '2rem', border: '1px solid #e0e0e0', borderRadius: '8px', padding: '1.5rem' }}>
        <h4 style={{ margin: '0 0 1rem 0' }}>Estado del Backend (/api/v1/health/):</h4>

        {loading && <p style={{ color: '#0066cc' }}>Consultando endpoint...</p>}

        {error && (
          <div style={{ background: '#ffebee', color: '#c62828', padding: '1rem', borderRadius: '6px' }}>
            <strong>Error de conexión:</strong> {error}
          </div>
        )}

        {healthData && (
          <div style={{ background: '#e8f5e9', color: '#2e7d32', padding: '1rem', borderRadius: '6px' }}>
            <strong>Respuesta exitosa:</strong>
            <pre style={{ margin: '0.5rem 0 0 0', background: 'rgba(0,0,0,0.05)', padding: '0.5rem', borderRadius: '4px' }}>
              {JSON.stringify(healthData, null, 2)}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}

export default App;
<h4>Keriot</h4>

// frontend/src/App.vue
<script setup>
import { ref, onMounted } from 'vue'

const health = ref(null)
const error = ref(null)
const loading = ref(true)

onMounted(async () => {
  try {
    const res = await fetch('http://localhost:8000/api/v1/health/')
    if (!res.ok) throw new Error(`HTTP ${res.status}: Error al conectar con la API`)
    health.value = await res.json()
  } catch (err) {
    error.value = err.message
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <main style="font-family: Arial, sans-serif; max-width: 800px; margin: 2rem auto; padding: 1.5rem; border: 1px solid #e2e8f0; border-radius: 8px;">
    <h1>🎮 GameStore — Panel de Control (Sprint 0)</h1>
    <p>Verificación de infraestructura multi-contenedor:</p>

    <div v-if="loading" style="color: #64748b;">
      Verificando estado de los servicios...
    </div>

    <div v-else-if="health" style="background: #f0fdf4; border: 1px solid #86efac; padding: 1rem; border-radius: 6px; color: #166534;">
      <h3>✅ Estado del Sistema: ONLINE</h3>
      <p><strong>Servicio:</strong> {{ health.service }}</p>
      <p><strong>Base de Datos (PostgreSQL):</strong> {{ health.database }}</p>
      <p><strong>Backend:</strong> Django REST Framework</p>
    </div>

    <div v-else-if="error" style="background: #fef2f2; border: 1px solid #fca5a5; padding: 1rem; border-radius: 6px; color: #991b1b;">
      <h3>❌ Error de Conexión</h3>
      <p>{{ error }}</p>
      <small>Revisa que el contenedor del backend esté corriendo en el puerto 8000 y CORS esté habilitado.</small>
    </div>
  </main>
</template>
